### ISSUE TITLE
Dropping 8.0.2 without error

### ISSUE THREAD

**Issue by eborden** [hvr/multi-ghc-travis#50]
Currently the v1 and v2 generators are dropping 8.0.2 without error when presented with a valid GHC version and 8.0.2

Input:
```
tested-with:   GHC == 7.10.2, GHC == 8.0.2
```

Output:
```
matrix:
   include:
     - env: CABALVER=1.22 GHCVER=7.10.2
       compiler: ": #GHC 7.10.2"
       addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2], sources: [hvr-ghc]}}
```
